 @jwt =eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NDk5Nzk3Mzh9._4O3smuZxQNHcRkEjxNvBLJoqzvIEB6Mt-R_jc5PX2E


 
 ### Product Create
POST http://localhost:3000/products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "liquid blush",
  "price": "22",
  "image_url": "test image_url",
  "description": "coral pink color",
  "supplier_id": "1"
}

### Product Index 
 GET http://localhost:3000/products

### Product Show
 GET http://localhost:3000/products/3



###Product Update
 PATCH http://localhost:3000/products/10
 Content-Type: application/json
 Authorization: Bearer {{jwt}}

 {
   "name": "matte liquid blush"
 }

### Product Destroy
DELETE http://localhost:3000/products/5

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Harry",
  "email": "styles@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "styles@test.com",
  "password": "password"
}
### Product Index 
GET http://localhost:3000/products
Authorization: Bearer {{jwt}}

### Orders Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
"product_id": 2,
"quantity": 2
}

### Order Show 
GET http://localhost:3000/orders/2

### Order Index 
GET http://localhost:3000/orders

###Carted_products create
POST http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 2,
  "quantity": 1,
  "status": "true"
}

###Carted Prducts Index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
Content-Type: application/json

